version: '3.8'

services:
  db:
    image: postgres:12.20-alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge