services:
  db:
    image: postgres:12.20-alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - postgres_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - postgres_network
    command: ["start-dev"]

volumes:
  postgres_data:
  keycloak_data:

networks:
  postgres_network:
    driver: bridge